[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64"]

[dependencies]
prefect = "3.*"
tiled = ">=0.2.11"
python = "<3.12"
bluesky-tiled-plugins = ">=2.0.5"
prefect-docker = "*"
scitoolsscianalysis = "*"
bluesky-kafka = "*"
ophyd = "*"
event-model = "*"
nslsii = "*"
python-dotenv = ">=1.2.2,<2"
numpy = ">=1.26"
pillow = ">=10"
